spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
  jpa:
    show-sql: false

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
